/*
 * File: common.h
 * Description:
 *   Contains shared definitions, macros, and data structures used across all source files.
 *   Defines the BoundedBuffer struct, constants (e.g., POISON_PILL), and includes
 *   required headers for pthreads, semaphores, and standard I/O.
 */


 #ifndef COMMON_H
#define COMMON_H

#include <stdio.h>
#include <stdlib.h>
#include <pthread.h>
#include <semaphore.h>
#include <time.h>

/* Project wide constants */
#define ITEMS_PER_PRODUCER 20
#define POISON_PILL_VALUE  -1

/* Item stored in the shared buffer */
typedef struct {
    int value;      /* random integer generated by producers */
    int is_poison;  /* 1 if this is a poison pill, 0 otherwise */
} Item;

/* Shared circular buffer and synchronization primitives */
typedef struct {
    Item *slots;           /* array of items */
    int capacity;          /* total number of slots */
    int head;              /* next index to write */
    int tail;              /* next index to read */

    int real_items_target; /* producers x ITEMS_PER_PRODUCER */
    int real_items_seen;   /* how many non poison items consumers removed */

    sem_t slots_free;      /* how many free positions */
    sem_t slots_used;      /* how many occupied positions */
    pthread_mutex_t lock;  /* protects buffer indices and counters */
} SharedBuffer;

/* Arguments passed to producer and consumer threads */
typedef struct {
    int id;                /* producer or consumer id starting from 1 */
    SharedBuffer *buffer;  /* pointer to shared buffer */
} ThreadArgs;

/* Thread function prototypes */
void *producer_thread(void *arg);
void *consumer_thread(void *arg);

/* High level runner that main will call */
int run_simulation(int producer_count, int consumer_count, int buffer_capacity);

#endif /* COMMON_H */
